extends:
  - airbnb
  - airbnb/hooks
  - prettier
  - prettier/react
env:
  browser: true
  node: true
  mocha: true
parser: babel-eslint
rules:
  quote-props:
    - 2
    - as-needed
  comma-dangle:
    - 2
    - always-multiline
  semi:
    - 2
    - never
  quotes:
    - 2
    - single
  jsx-quotes:
    - 2
    - prefer-double
  react/jsx-pascal-case: 2
  react/jsx-filename-extension:
    - 1
    - allow: as-needed
  react/jsx-props-no-spreading: 0
  react/prop-types: 0
  react/jsx-fragments: 0
  react/jsx-no-duplicate-props:
    - 1
    - ignoreCase: false
  no-nested-ternary: 0
  import/no-unresolved: 0
  import/no-named-as-default: 0
  no-unused-expressions: 0
  indent:
    - 2
    - 2
    - SwitchCase: 1
  no-console: 0
  no-alert: 0
  id-length: 0
  no-script-url: 0
  import/no-extraneous-dependencies: 0
  no-underscore-dangle: 0
  global-require: 0
  import/newline-after-import: 0
  import/extensions: 0
  prefer-template: 0
  max-len: 0
  react/prefer-stateless-function: 0
  react/forbid-prop-types: 0
  jsx-a11y/href-no-hash: off
  function-paren-newline: 0
  react/no-typos: 0
  object-curly-newline: 0
  jsx-a11y/anchor-is-valid: 0
  react/default-props-match-prop-types: 0
  arrow-parens: 0
  jsx-a11y/label-has-associated-control: 0
  jsx-a11y/label-has-for:
    - 2
    - required:
        every:
          - id
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
  linebreak-style: 0
  react/state-in-constructor:
    - 2
    - never
plugins:
  - unicorn
  - react
  - import
  - jsx-a11y
  - react-hooks
settings:
  import/parser: babel-eslint
  import/resolve:
    moduleDirectory:
      - node_modules
      - src
globals: {}
